blockExoticSubdeps: true
allowBuilds:
  "@firebase/util": true
  "@google/genai": true
  "@sentry/cli": true
  esbuild: true
  protobufjs: true
onlyBuiltDependencies:
  - "@firebase/util"
  - "@google/genai"
  - "@sentry/cli"
  - esbuild
  - protobufjs
