name: Draft Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  update-draft-release:
    name: Update Draft Release Notes
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
